### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by dimensi** [Paul-Browne/lazyestload.js#2]
Hi, i not use your library, i simple came from some news article. I look on your code and you not handle case when image not loaded and user continuously scrolling and user got this.
![image](https://user-images.githubusercontent.com/11390039/44007736-68582840-9ea3-11e8-99cb-0e212598603a.png)

**Comment by Paul-Browne** [comment]
The "memory leak" is simply because there is a scroll event listener attached to the window. 

This has been debounced [read more here](https://paulbrowne.xyz/debouncing) so that it only fires the part of the script that replaces the images every fifth of a second. If there are no `<img class="lazyestload">` in the DOM then nothing happens.

But I will look into removing the scroll event from the window after all the images have been replaced

**Comment by Paul-Browne** [comment]
https://github.com/Paul-Browne/lazyestload.js/blob/master/lazyload.js

This script removes the scroll event listener if there are no `<img class="lazyload">` in the DOM

**Comment by didxga** [comment]
```
images[i].addEventListener('load', function() {

                    // remove the class lazyload

                    this.classList.remove("lazyload");
                });
```
From the above code, I saw that the CSS Class `lazyload` is removed only when the image is loaded, this can cause issue, when user is continuously scrolling, which make this code:

```
if (yPosition <= offset) {

                if (images[i].getAttribute("data-src")) {
                    images[i].src = images[i].getAttribute("data-src");
                }
```
to reset the <img> src again and again.

**Comment by ChriStef** [comment]
...

> https://github.com/Paul-Browne/lazyestload.js/blob/master/lazyload.js
> 
> This script removes the scroll event listener if there are no `<img class="lazyload">` in the DOM

Sorry but 404, is this issue still active? What can we do?
